#!/bin/sh
#
# /etc/init.d/tcpfwd
# TCP connection forwarder
#
# chkconfig: 2345 80 05
# description: TCP connection forwarder daemon
# config: /etc/tcpfwd/tcpfwd.conf
# pidfile: /temp/tcpfwd.lock

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog="tcpfwd"

start() {
	echo -n $"Starting $prog:"
	. /usr/bin/tcpfwd -c /etc/tcpfwd/tcpfwd.conf -d
	RETVAL=$?
	if [ "$RETVAL" = 0 ]; then
		touch /var/lock/subsys/$prog
		success "Starting $prog service"
	else
		failure "Starting $prog service"
	fi
	echo
}

stop() {
	echo -n $"Stopping $prog:"
	killproc $prog -TERM
	RETVAL=$?
	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status $prog
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		RETVAL=1
		;;
esac
exit $RETVAL
	
